---
kind: Namespace
apiVersion: v1
metadata:
  name: handson
  labels:
    name: handson
---
apiVersion: v1
kind: Service
metadata:
  name: sample-headless
  namespace: handson
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 80
      targetPort: 80
  selector:
    app: sample-app
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sample-statefulset-headless
  namespace: handson
spec:
  serviceName: sample-headless #HeadlessServiceの名前を指定
  replicas: 3
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: nginx
          image: hokekyo1210/nginx-echoip:v1
          ports:
            - containerPort: 80
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
